### ISSUE TITLE
AP should use external WiFi chipset

### ISSUE THREAD

**Issue by dbcarelli** [missionmule/muleOS-gen#1]
Currently, the AP uses wlan0. However, when a USB WiFi module is added, it gets set to wlan1 and is not used for the AP. 

-Why not disable the onboard wifi?
because we need an easy way to access internet.

**Comment by dbcarelli** [comment]
actually, it seems that with the new wifi modules, they take on wlan0--this is what i remember happening with reefRover

**Comment by zanemountcastle** [comment]
`wlan0` is the interface over which the AP works.

Is this issue resolved then, @dbcarelli?

**Comment by dbcarelli** [comment]
not yet. And, yes, wlan0 is the interface that is used for the AP. The issue is regarding what chipset actually gets assigned the name wlan0.

**Comment by zanemountcastle** [comment]
Looking into this further, Raspbian [disables](https://www.raspberrypi.org/forums/viewtopic.php?t=198687) "predictable interface names" by default and the interface used for onboard WiFi and external WiFi chipsets can vary depending on the device's interaction with the kernel.

[Bad practice approach](https://www.raspberrypi.org/forums/viewtopic.php?t=198687): Enable predictable interface names (which show up as `wlan0aabbccddee` depending on the device's MAC address. This would require each device to be independently provisioned and would pair each device with a single dongle. Not scalable.

[Better practice](https://www.raspberrypi.org/forums/viewtopic.php?f=36&t=198946): Set interface by machine interfaces. Therefore, built-in Wi-Fi on the `SDIO` interface can be relegated `wlan1` and WiFi USB devices can be set to `wlan0`. This would limit the predictable interface to *one* USB WiFi dongle. Beyond that, it the `wlan` interface for the dongle in consideration could be at `wlan0`, `wlan1`, `wlan2`, or `wlan3`.  This should not affect us but should be recognized.

**Comment by zanemountcastle** [comment]
This was resolved in PR #2. Closing.
